from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any

from .boundary_observations import QuarterHourObservation, derive_quarter_hour_observation, require_utc
from .order_book import Level2OrderBook


def floor_to_quarter_hour(timestamp: datetime) -> datetime:
    """Return the exact quarter-hour boundary at or before ``timestamp`` (UTC)."""
    utc = require_utc(timestamp)
    minute = (utc.minute // 15) * 15
    return utc.replace(minute=minute, second=0, microsecond=0)


def _event_time(event: Mapping[str, Any]) -> datetime | None:
    return event.get("event_time_utc") or event.get("time_utc") or event.get("envelope_time_utc")


@dataclass(slots=True)
class BoundaryEventProcessor:
    """Operational, provisional boundary processor for parsed events.

    An observation is derived for every exact quarter-hour boundary crossed
    in this stream. The final canonical ledger must instead be generated by
    :func:`replay_recorded_frames` over sealed source frames.
    """

    product_id: str
    heartbeat_timeout_seconds: float = 5.0
    last_heartbeat_at: datetime | None = None
    gap_since_sync: bool = True
    _last_boundary_checked: datetime | None = field(default=None, repr=False)

    def observe_heartbeat(self, *, time_utc: datetime) -> None:
        self.last_heartbeat_at = require_utc(time_utc)

    def note_gap(self) -> None:
        self.gap_since_sync = True

    def note_synced(self) -> None:
        self.gap_since_sync = False

    def observe(self, *, book: Level2OrderBook, event_time_utc: datetime | None) -> list[QuarterHourObservation]:
        """Emit observations for every quarter-hour boundary newly crossed as of ``event_time_utc``."""
        if event_time_utc is None:
            return []
        event_time_utc = require_utc(event_time_utc)
        floor = floor_to_quarter_hour(event_time_utc)
        if self._last_boundary_checked is None:
            # Bootstrap: allow the very first quarter-hour containing this event to be
            # eligible for emission without walking arbitrarily far into the past.
            self._last_boundary_checked = floor - timedelta(minutes=15)
        boundaries: list[datetime] = []
        cursor = self._last_boundary_checked + timedelta(minutes=15)
        while cursor <= floor:
            boundaries.append(cursor)
            cursor += timedelta(minutes=15)
        observations: list[QuarterHourObservation] = []
        for boundary in boundaries:
            if book.is_synced():
                observations.append(
                    derive_quarter_hour_observation(
                        book=book, timestamp_utc=boundary, product_id=self.product_id,
                        last_heartbeat_at=self.last_heartbeat_at,
                        heartbeat_timeout_seconds=self.heartbeat_timeout_seconds,
                        integrity_reason="sequence_gap" if self.gap_since_sync else None,
                    )
                )
            self._last_boundary_checked = boundary
        return observations


def process_parsed_event(
    *,
    event: Mapping[str, Any],
    book: Level2OrderBook,
    processor: BoundaryEventProcessor,
) -> list[QuarterHourObservation]:
    """Apply a parsed event for provisional live processing or legacy replay."""
    event_type = event.get("type")
    observations = processor.observe(book=book, event_time_utc=_event_time(event))
    if event_type == "heartbeat":
        time_utc = event.get("time_utc")
        processor.observe_heartbeat(time_utc=time_utc or datetime.now(timezone.utc))
        return observations
    if event_type not in {"snapshot", "l2_data"}:
        return observations
    sequence_num = event.get("sequence_num")
    if sequence_num is not None and book.last_sequence_num is not None and sequence_num <= book.last_sequence_num:
        # A redelivered/duplicate message for this connection epoch: its
        # effect is already reflected in the book, so it is safely dropped
        # without invalidating the book or marking a gap.
        return observations
    try:
        if event_type == "snapshot":
            book.reset()
            updates = event.get("updates", [])
            book.apply_snapshot(
                product_id=book.product_id,
                levels={
                    "bid": [u for u in updates if u["side"] == "bid"],
                    "ask": [u for u in updates if u["side"] == "ask"],
                },
            )
        else:
            book.apply_updates(event.get("updates", []))
    except ValueError:
        processor.note_gap()
        return observations
    if sequence_num is not None:
        book.last_sequence_num = sequence_num
    processor.note_synced()
    return observations


def _connection_field(connection: Any, name: str) -> Any:
    return connection.get(name) if isinstance(connection, Mapping) else getattr(connection, name, None)


def _envelope_integrity_reason(
    bids: Mapping[float, float],
    asks: Mapping[float, float],
    error: Exception,
) -> str:
    if "crossed" in str(error).lower():
        return "crossed_book"
    if not bids:
        return "missing_bid"
    if not asks:
        return "missing_ask"
    return "malformed_source_state"


@dataclass(slots=True)
class _ReplayL2Envelope:
    effective_time_utc: datetime
    kind: str
    updates: list[Mapping[str, Any]]
    sequence_num: int


def replay_recorded_frames(
    frames: Iterable[tuple[bytes, str, int]],
    *,
    product_id: str,
    session_id: str,
    heartbeat_timeout_seconds: float,
    connections: Iterable[Any] | None = None,
    session_started_at_utc: datetime | None = None,
    session_completed_at_utc: datetime | None = None,
    derived_at_utc: datetime | None = None,
) -> list[QuarterHourObservation]:
    """Finalize raw frames using connection delivery order for causal L2 state.

    Connection diagnostics may be mappings or objects with ``connection_id``,
    ``connected_at_utc`` and ``disconnected_at_utc`` attributes. A missing
    disconnect is bounded by the next connection's start when known.

    Complete L2 envelopes are atomic. Their effective source time is the
    normalized event time (the maximum update time for incremental envelopes),
    but per-update times never reorder mutations across envelopes. At each
    boundary, replay commits the longest delivery-ordered prefix with
    effective times at or before that boundary; a future envelope blocks all
    later envelopes from leapfrogging it.
    """
    from btc_quarter_hour_engine.acquisition.coinbase_websocket import parse_coinbase_ws_message

    if heartbeat_timeout_seconds < 0:
        raise ValueError("Heartbeat timeout must be nonnegative")
    start = require_utc(session_started_at_utc) if session_started_at_utc is not None else None
    end = require_utc(session_completed_at_utc) if session_completed_at_utc is not None else None
    if start is not None and end is not None and end < start:
        raise ValueError("Session completion precedes session start")

    # Preserve recorded delivery order independently for each connection.
    deliveries: dict[str, list[tuple[int, int, bytes]]] = {}
    for arrival, (raw, connection_id, frame_index) in enumerate(frames):
        if not isinstance(raw, bytes):
            raise TypeError("Recorded frames must retain their original bytes")
        deliveries.setdefault(connection_id, []).append((frame_index, arrival, raw))

    metadata = {
        _connection_field(c, "connection_id"): c for c in (connections or ())
    }
    ids = list(dict.fromkeys([*metadata, *deliveries]))
    controls: dict[str, list[tuple[datetime, int, str, Any, int | None]]] = {}
    l2_envelopes: dict[str, list[_ReplayL2Envelope]] = {}
    bounds: dict[str, tuple[datetime | None, datetime | None]] = {}
    source_end_times: dict[str, datetime | None] = {}
    observed_times: list[datetime] = []
    for connection_id in ids:
        sequence: int | None = None
        invalid = False
        wire_book = Level2OrderBook(product_id=product_id)
        connection_controls: list[tuple[datetime, int, str, Any, int | None]] = []
        connection_l2: list[_ReplayL2Envelope] = []
        first_time: datetime | None = None
        last_time: datetime | None = None
        for _frame_index, arrival, raw in deliveries.get(connection_id, []):
            try:
                event = parse_coinbase_ws_message(raw)
            except (ValueError, UnicodeError):
                invalid = True
                if last_time is not None:
                    connection_controls.append((last_time, arrival, "malformed", None, sequence))
                continue
            kind = event.get("type")
            envelope = event["envelope"]
            envelope_time = event.get("envelope_time_utc") or event.get("time_utc") or envelope.timestamp_utc
            if envelope_time is not None:
                envelope_time = require_utc(envelope_time)
            current = envelope.sequence_num
            if sequence is not None and current <= sequence:
                continue
            if sequence is not None and current > sequence + 1:
                gap_time = envelope_time
                if kind == "snapshot":
                    gap_time = require_utc(event["event_time_utc"])
                elif kind == "heartbeat":
                    gap_time = require_utc(event["time_utc"])
                elif kind == "l2_data":
                    gap_time = require_utc(event["event_time_utc"])
                    update_times = [
                        require_utc(update.get("event_time_utc") or gap_time)
                        for update in event["updates"]
                    ]
                    observed_times.extend(update_times)
                    if update_times:
                        first_time = min(first_time, *update_times) if first_time else min(update_times)
                        last_time = max(last_time, *update_times) if last_time else max(update_times)
                if gap_time is None:
                    continue
                invalid = True
                connection_controls.append((gap_time, arrival, "gap", None, current))
                observed_times.append(gap_time)
                first_time = min(first_time, gap_time) if first_time else gap_time
                last_time = max(last_time, gap_time) if last_time else gap_time
                sequence = current
                continue
            sequence = current
            if kind not in {"snapshot", "l2_data", "heartbeat"}:
                continue
            if kind == "snapshot":
                event_time = require_utc(event["event_time_utc"])
            elif kind == "heartbeat":
                event_time = require_utc(event["time_utc"])
            else:
                event_time = require_utc(event["event_time_utc"])
                times = [
                    require_utc(update.get("event_time_utc") or event_time)
                    for update in event["updates"]
                ]
                observed_times.extend(times)
                if times:
                    first_time = min(first_time, *times) if first_time is not None else min(times)
                    last_time = max(last_time, *times) if last_time is not None else max(times)
            if event_time is None:
                continue
            observed_times.append(event_time)
            first_time = min(first_time, event_time) if first_time else event_time
            last_time = max(last_time, event_time) if last_time else event_time
            if kind == "heartbeat":
                if not invalid:
                    connection_controls.append((event_time, arrival, "heartbeat", None, None))
                continue
            if event["product_id"] != product_id:
                continue
            if invalid:
                continue
            updates = event["updates"]
            if kind == "snapshot":
                try:
                    wire_book.apply_snapshot(
                        product_id=product_id,
                        levels={
                            "bid": [update for update in updates if update["side"] == "bid"],
                            "ask": [update for update in updates if update["side"] == "ask"],
                        },
                    )
                except (ValueError, KeyError, TypeError) as exc:
                    invalid = True
                    failure_reason = _envelope_integrity_reason(wire_book.bids, wire_book.asks, exc)
                    connection_controls.append((
                        event_time, arrival, "envelope_invalid", (failure_reason, str(exc)), current,
                    ))
                else:
                    connection_l2.append(_ReplayL2Envelope(event_time, kind, updates, current))
            else:
                if wire_book.is_synced():
                    try:
                        wire_book.apply_updates(updates)
                    except (ValueError, KeyError, TypeError) as exc:
                        invalid = True
                        failure_reason = _envelope_integrity_reason(wire_book.bids, wire_book.asks, exc)
                        connection_controls.append((
                            event_time, arrival, "envelope_invalid", (failure_reason, str(exc)), current,
                        ))
                    else:
                        connection_l2.append(_ReplayL2Envelope(event_time, kind, updates, current))
                else:
                    connection_l2.append(_ReplayL2Envelope(event_time, kind, updates, current))
        meta = metadata.get(connection_id)
        # Connection diagnostics are wall-clock ingest times, not Coinbase
        # source times. Comparing them to event-time boundaries mixes clocks.
        disconnected = _connection_field(meta, "source_disconnected_at_utc")
        disconnected = require_utc(disconnected) if disconnected is not None else None
        bounds[connection_id] = (first_time, disconnected)
        source_end_times[connection_id] = last_time
        controls[connection_id] = sorted(connection_controls, key=lambda action: (action[0], action[1]))
        l2_envelopes[connection_id] = connection_l2

    if not observed_times and (start is None or end is None):
        return []
    start = min(start, *observed_times) if start is not None and observed_times else (
        start if start is not None else min(observed_times)
    )
    end = max(end, *observed_times) if end is not None and observed_times else (
        end if end is not None else max(observed_times)
    )
    if end < start:
        return []
    derived_at = require_utc(derived_at_utc) if derived_at_utc is not None else end
    boundary = floor_to_quarter_hour(start)
    if boundary < start:
        boundary += timedelta(minutes=15)
    # The connection epoch active at a boundary is the last one started by
    # that instant. A disconnected interval cannot inherit its old book.
    ordered_ids = sorted(ids, key=lambda cid: (bounds[cid][0] or datetime.max.replace(tzinfo=timezone.utc), ids.index(cid)))
    for cid in ordered_ids[:-1]:
        bounds[cid] = (bounds[cid][0], source_end_times[cid] or bounds[cid][0])
    books = {cid: Level2OrderBook(product_id=product_id) for cid in ids}
    control_cursors = {cid: 0 for cid in ids}
    l2_cursors = {cid: 0 for cid in ids}
    heartbeats: dict[str, datetime | None] = {cid: None for cid in ids}
    state_times: dict[str, datetime | None] = {cid: None for cid in ids}
    state_sequences: dict[str, int | None] = {cid: None for cid in ids}
    reasons: dict[str, str | None] = {cid: None for cid in ids}
    has_snapshot: dict[str, bool] = {cid: False for cid in ids}
    result: list[QuarterHourObservation] = []
    while boundary <= end:
        active: str | None = None
        for cid in ordered_ids:
            connected, disconnected = bounds[cid]
            if connected is not None and connected <= boundary:
                active = cid
        if active is not None:
            connected, disconnected = bounds[active]
            if disconnected is not None and disconnected < boundary:
                active = None
        if active is None:
            result.append(
                derive_quarter_hour_observation(
                    book=Level2OrderBook(product_id=product_id), timestamp_utc=boundary,
                    product_id=product_id, session_id=session_id, derived_at_utc=derived_at,
                    heartbeat_timeout_seconds=heartbeat_timeout_seconds,
                    integrity_reason="connection_unhealthy" if deliveries else "no_synced_snapshot",
                )
            )
        else:
            book = books[active]
            envelopes = l2_envelopes[active]
            while (
                reasons[active] is None
                and l2_cursors[active] < len(envelopes)
                and envelopes[l2_cursors[active]].effective_time_utc <= boundary
            ):
                envelope_action = envelopes[l2_cursors[active]]
                l2_cursors[active] += 1
                try:
                    if envelope_action.kind == "snapshot":
                        book.apply_snapshot(
                            product_id=product_id,
                            levels={
                                "bid": [update for update in envelope_action.updates if update["side"] == "bid"],
                                "ask": [update for update in envelope_action.updates if update["side"] == "ask"],
                            },
                        )
                        has_snapshot[active] = True
                        state_times[active] = envelope_action.effective_time_utc
                        state_sequences[active] = envelope_action.sequence_num
                    elif has_snapshot[active]:
                        book.apply_updates(envelope_action.updates)
                        state_times[active] = envelope_action.effective_time_utc
                        state_sequences[active] = envelope_action.sequence_num
                except (ValueError, KeyError, TypeError) as exc:
                    reasons[active] = _envelope_integrity_reason(book.bids, book.asks, exc)
                    book.invalidate(str(exc))

            connection_controls = controls[active]
            while (
                control_cursors[active] < len(connection_controls)
                and connection_controls[control_cursors[active]][0] <= boundary
            ):
                when, _, kind, payload, _sequence = connection_controls[control_cursors[active]]
                control_cursors[active] += 1
                if kind == "heartbeat":
                    heartbeats[active] = when
                elif reasons[active] is None:
                    if kind == "gap":
                        reasons[active] = "sequence_gap"
                        book.invalidate("sequence gap")
                    elif kind == "malformed":
                        reasons[active] = "malformed_source_state"
                        book.invalidate("malformed_source_state")
                    elif kind == "envelope_invalid":
                        reasons[active], message = payload
                        book.invalidate(message)
            result.append(
                derive_quarter_hour_observation(
                    book=book, timestamp_utc=boundary, product_id=product_id,
                    session_id=session_id, connection_id=active, source_state_time_utc=state_times[active],
                    source_sequence_num=state_sequences[active], derived_at_utc=derived_at,
                    last_heartbeat_at=heartbeats[active], heartbeat_timeout_seconds=heartbeat_timeout_seconds,
                    integrity_reason=reasons[active],
                )
            )
        boundary += timedelta(minutes=15)
    return result


def _source_times(event: Mapping[str, Any]) -> list[datetime]:
    kind = event.get("type")
    if kind == "heartbeat":
        return [require_utc(event["time_utc"])]
    if kind == "snapshot":
        return [require_utc(event["event_time_utc"])]
    if kind == "l2_data":
        effective = require_utc(event["event_time_utc"])
        return [effective, *[
            require_utc(update.get("event_time_utc") or effective)
            for update in event["updates"]
        ]]
    return []


def _bounded_session_summary(
    frames_factory: Callable[[], Iterable[tuple[bytes, str, int, datetime]]],
    connections: Iterable[Any],
) -> tuple[list[str], dict[str, tuple[datetime | None, datetime | None]], datetime | None, datetime | None, tuple[datetime, datetime] | None, bool]:
    from btc_quarter_hour_engine.acquisition.coinbase_websocket import parse_coinbase_ws_message

    metadata = {_connection_field(c, "connection_id"): c for c in connections}
    ids = list(metadata)
    sequence_by_connection: dict[str, int] = {}
    first_last: dict[str, tuple[datetime | None, datetime | None]] = {}
    observed_min: datetime | None = None
    observed_max: datetime | None = None
    first_sample: tuple[datetime, datetime] | None = None
    last_sample: tuple[datetime, datetime] | None = None
    has_deliveries = False

    def note(connection_id: str, timestamp: datetime) -> None:
        nonlocal observed_min, observed_max
        first, last = first_last.get(connection_id, (None, None))
        first_last[connection_id] = (
            min(first, timestamp) if first is not None else timestamp,
            max(last, timestamp) if last is not None else timestamp,
        )
        observed_min = min(observed_min, timestamp) if observed_min is not None else timestamp
        observed_max = max(observed_max, timestamp) if observed_max is not None else timestamp

    for raw, connection_id, _frame_index, ingest_time in frames_factory():
        has_deliveries = True
        if connection_id not in metadata and connection_id not in ids:
            ids.append(connection_id)
        try:
            event = parse_coinbase_ws_message(raw)
        except (ValueError, UnicodeError):
            continue
        kind = event.get("type")
        source_time = (
            event.get("time_utc") if kind == "heartbeat"
            else event.get("envelope_time_utc") if kind == "snapshot"
            else event.get("event_time_utc") if kind == "l2_data"
            else None
        )
        if kind in {"snapshot", "l2_data", "heartbeat"} and source_time is not None:
            sample = (require_utc(source_time), require_utc(ingest_time))
            if first_sample is None:
                first_sample = sample
            last_sample = sample

        sequence = sequence_by_connection.get(connection_id)
        current = event["envelope"].sequence_num
        if sequence is not None and current <= sequence:
            continue
        event_times = _source_times(event)
        if sequence is not None and current > sequence + 1:
            if kind == "snapshot":
                gap_time = require_utc(event["event_time_utc"])
            elif kind == "heartbeat":
                gap_time = require_utc(event["time_utc"])
            elif kind == "l2_data":
                for timestamp in event_times:
                    note(connection_id, timestamp)
                gap_time = require_utc(event["event_time_utc"])
            else:
                envelope_time = event.get("envelope_time_utc") or event.get("time_utc") or event["envelope"].timestamp_utc
                gap_time = require_utc(envelope_time)
            sequence_by_connection[connection_id] = current
            note(connection_id, gap_time)
            continue
        sequence_by_connection[connection_id] = current
        if kind not in {"snapshot", "l2_data", "heartbeat"}:
            continue
        for timestamp in event_times:
            note(connection_id, timestamp)

    return ids, first_last, observed_min, observed_max, (
        (first_sample, last_sample) if first_sample is not None and last_sample is not None else None
    ), has_deliveries


def _replay_connection_at_boundary(
    frames_factory: Callable[[], Iterable[tuple[bytes, str, int, datetime]]],
    *,
    connection_id: str,
    boundary: datetime,
    product_id: str,
) -> tuple[Level2OrderBook, datetime | None, datetime | None, int | None, str | None]:
    from btc_quarter_hour_engine.acquisition.coinbase_websocket import parse_coinbase_ws_message

    sequence: int | None = None
    invalid = False
    wire_book = Level2OrderBook(product_id=product_id)
    book = Level2OrderBook(product_id=product_id)
    has_snapshot = False
    state_time: datetime | None = None
    state_sequence: int | None = None
    heartbeat: datetime | None = None
    first_control: tuple[datetime, int, str, Any] | None = None
    blocked = False
    last_time: datetime | None = None
    canonical_reason: str | None = None
    canonical_message: str | None = None

    for arrival, (raw, frame_connection_id, _frame_index, _ingest_time) in enumerate(frames_factory()):
        if frame_connection_id != connection_id:
            continue
        try:
            event = parse_coinbase_ws_message(raw)
        except (ValueError, UnicodeError):
            invalid = True
            if last_time is not None:
                candidate = (last_time, arrival, "malformed", None)
                first_control = min(first_control, candidate) if first_control is not None else candidate
            continue
        kind = event.get("type")
        envelope = event["envelope"]
        envelope_time = event.get("envelope_time_utc") or event.get("time_utc") or envelope.timestamp_utc
        current = envelope.sequence_num
        if sequence is not None and current <= sequence:
            continue
        if sequence is not None and current > sequence + 1:
            if kind == "snapshot":
                gap_time = require_utc(event["event_time_utc"])
            elif kind == "heartbeat":
                gap_time = require_utc(event["time_utc"])
            elif kind == "l2_data":
                gap_time = require_utc(event["event_time_utc"])
                last_time = max(last_time, gap_time) if last_time is not None else gap_time
                for update in event["updates"]:
                    update_time = require_utc(update.get("event_time_utc") or gap_time)
                    last_time = max(last_time, update_time)
            else:
                gap_time = require_utc(envelope_time)
            invalid = True
            candidate = (gap_time, arrival, "gap", None)
            first_control = min(first_control, candidate) if first_control is not None else candidate
            last_time = max(last_time, gap_time) if last_time is not None else gap_time
            sequence = current
            continue
        sequence = current
        if kind not in {"snapshot", "l2_data", "heartbeat"}:
            continue
        if kind == "snapshot":
            event_time = require_utc(event["event_time_utc"])
        elif kind == "heartbeat":
            event_time = require_utc(event["time_utc"])
        else:
            event_time = require_utc(event["event_time_utc"])
            for update in event["updates"]:
                update_time = require_utc(update.get("event_time_utc") or event_time)
                last_time = max(last_time, update_time) if last_time is not None else update_time
        last_time = max(last_time, event_time) if last_time is not None else event_time
        if kind == "heartbeat":
            if not invalid and event_time <= boundary:
                heartbeat = max(heartbeat, event_time) if heartbeat is not None else event_time
            continue
        if event["product_id"] != product_id or invalid:
            continue

        updates = event["updates"]
        envelope_invalid: tuple[str, str] | None = None
        if kind == "snapshot":
            try:
                wire_book.apply_snapshot(
                    product_id=product_id,
                    levels={
                        "bid": [update for update in updates if update["side"] == "bid"],
                        "ask": [update for update in updates if update["side"] == "ask"],
                    },
                )
            except (ValueError, KeyError, TypeError) as exc:
                envelope_invalid = (_envelope_integrity_reason(wire_book.bids, wire_book.asks, exc), str(exc))
        elif wire_book.is_synced():
            try:
                wire_book.apply_updates(updates)
            except (ValueError, KeyError, TypeError) as exc:
                envelope_invalid = (_envelope_integrity_reason(wire_book.bids, wire_book.asks, exc), str(exc))

        if envelope_invalid is not None:
            invalid = True
            candidate = (event_time, arrival, "envelope_invalid", envelope_invalid)
            first_control = min(first_control, candidate) if first_control is not None else candidate
            continue

        if not blocked and canonical_reason is None:
            if event_time > boundary:
                blocked = True
            else:
                try:
                    if kind == "snapshot":
                        book.apply_snapshot(
                            product_id=product_id,
                            levels={
                                "bid": [update for update in updates if update["side"] == "bid"],
                                "ask": [update for update in updates if update["side"] == "ask"],
                            },
                        )
                        has_snapshot = True
                        state_time = event_time
                        state_sequence = current
                    elif has_snapshot:
                        book.apply_updates(updates)
                        state_time = event_time
                        state_sequence = current
                except (ValueError, KeyError, TypeError) as exc:
                    canonical_reason = _envelope_integrity_reason(book.bids, book.asks, exc)
                    canonical_message = str(exc)
                    book.invalidate(str(exc))

    if canonical_reason is not None:
        book.invalidate(canonical_message or canonical_reason)
        return book, heartbeat, state_time, state_sequence, canonical_reason
    if first_control is not None and first_control[0] <= boundary:
        kind = first_control[2]
        if kind in {"gap", "malformed", "envelope_invalid"}:
            reason = (
                "sequence_gap" if kind == "gap"
                else "malformed_source_state" if kind == "malformed"
                else first_control[3][0]
            )
            message = (
                "sequence gap" if kind == "gap"
                else "malformed_source_state" if kind == "malformed"
                else first_control[3][1]
            )
            book.invalidate(message)
            return book, heartbeat, state_time, state_sequence, reason
        if kind == "canonical_invalid":
            return book, heartbeat, state_time, state_sequence, first_control[3]
    return book, heartbeat, state_time, state_sequence, None


def replay_recorded_frames_bounded(
    frames_factory: Callable[[], Iterable[tuple[bytes, str, int, datetime]]],
    *,
    product_id: str,
    session_id: str,
    heartbeat_timeout_seconds: float,
    connections: Iterable[Any] | None = None,
    session_started_at_utc: datetime | None = None,
    session_completed_at_utc: datetime | None = None,
    derived_at_utc: datetime | None = None,
) -> list[QuarterHourObservation]:
    """Replay a repeatable durable frame source without retaining session history."""
    if heartbeat_timeout_seconds < 0:
        raise ValueError("Heartbeat timeout must be nonnegative")
    start = require_utc(session_started_at_utc) if session_started_at_utc is not None else None
    end = require_utc(session_completed_at_utc) if session_completed_at_utc is not None else None
    if start is not None and end is not None and end < start:
        raise ValueError("Session completion precedes session start")
    connection_records = list(connections or ())
    ids, first_last, observed_min, observed_max, samples, has_deliveries = _bounded_session_summary(
        frames_factory, connection_records,
    )
    if samples is not None:
        first_source, first_ingest = samples[0]
        last_source, last_ingest = samples[1]
        if start is not None:
            start = first_source - max(timedelta(0), first_ingest - start)
        if end is not None:
            end = last_source + max(timedelta(0), end - last_ingest)
    if observed_min is None and (start is None or end is None):
        return []
    start = min(start, observed_min) if start is not None and observed_min is not None else (start or observed_min)
    end = max(end, observed_max) if end is not None and observed_max is not None else (end or observed_max)
    if start is None or end is None or end < start:
        return []
    derived_at = require_utc(derived_at_utc) if derived_at_utc is not None else end
    boundary = floor_to_quarter_hour(start)
    if boundary < start:
        boundary += timedelta(minutes=15)
    metadata = {_connection_field(c, "connection_id"): c for c in connection_records}
    for connection_id in ids:
        metadata.setdefault(connection_id, None)
    ordered_ids = sorted(
        ids,
        key=lambda cid: (
            first_last.get(cid, (None, None))[0] or datetime.max.replace(tzinfo=timezone.utc),
            ids.index(cid),
        ),
    )
    bounds: dict[str, tuple[datetime | None, datetime | None]] = {}
    for connection_id in ids:
        meta = metadata.get(connection_id)
        disconnected = _connection_field(meta, "source_disconnected_at_utc")
        if disconnected is not None:
            disconnected = require_utc(disconnected)
        bounds[connection_id] = (first_last.get(connection_id, (None, None))[0], disconnected)
    for cid in ordered_ids[:-1]:
        bounds[cid] = (bounds[cid][0], first_last.get(cid, (None, None))[1] or bounds[cid][0])

    result: list[QuarterHourObservation] = []
    while boundary <= end:
        active: str | None = None
        for cid in ordered_ids:
            connected, _disconnected = bounds[cid]
            if connected is not None and connected <= boundary:
                active = cid
        if active is not None:
            connected, disconnected = bounds[active]
            if disconnected is not None and disconnected < boundary:
                active = None
        if active is None:
            result.append(
                derive_quarter_hour_observation(
                    book=Level2OrderBook(product_id=product_id),
                    timestamp_utc=boundary,
                    product_id=product_id,
                    session_id=session_id,
                    derived_at_utc=derived_at,
                    heartbeat_timeout_seconds=heartbeat_timeout_seconds,
                    integrity_reason="connection_unhealthy" if has_deliveries else "no_synced_snapshot",
                )
            )
        else:
            book, heartbeat, state_time, state_sequence, reason = _replay_connection_at_boundary(
                frames_factory,
                connection_id=active,
                boundary=boundary,
                product_id=product_id,
            )
            result.append(
                derive_quarter_hour_observation(
                    book=book,
                    timestamp_utc=boundary,
                    product_id=product_id,
                    session_id=session_id,
                    connection_id=active,
                    source_state_time_utc=state_time,
                    source_sequence_num=state_sequence,
                    derived_at_utc=derived_at,
                    last_heartbeat_at=heartbeat,
                    heartbeat_timeout_seconds=heartbeat_timeout_seconds,
                    integrity_reason=reason,
                )
            )
        boundary += timedelta(minutes=15)
    return result


@dataclass(slots=True)
class CanonicalReplayAccumulator:
    """Bounded-memory canonical finalizer backed by durable raw segment iteration."""

    frames_factory: Callable[[], Iterable[tuple[bytes, str, int, datetime]]]
    product_id: str
    session_id: str
    heartbeat_timeout_seconds: float
    connections_factory: Callable[[], Iterable[Any]]
    frame_count: int = 0
    connection_ids: set[str | None] = field(default_factory=set)

    def consume(self, raw: bytes, connection_id: str | None, frame_index: int) -> None:
        if not isinstance(raw, bytes):
            raise TypeError("Recorded frames must retain their original bytes")
        if frame_index < 0:
            raise ValueError("frame_index must be nonnegative")
        self.frame_count += 1
        self.connection_ids.add(connection_id)

    def finalize(
        self,
        *,
        session_started_at_utc: datetime | None,
        session_completed_at_utc: datetime | None,
        derived_at_utc: datetime,
    ) -> list[QuarterHourObservation]:
        return replay_recorded_frames_bounded(
            self.frames_factory,
            product_id=self.product_id,
            session_id=self.session_id,
            heartbeat_timeout_seconds=self.heartbeat_timeout_seconds,
            connections=self.connections_factory(),
            session_started_at_utc=session_started_at_utc,
            session_completed_at_utc=session_completed_at_utc,
            derived_at_utc=derived_at_utc,
        )


def replay_events(
    events: Iterable[Mapping[str, Any]],
    *,
    product_id: str,
    heartbeat_timeout_seconds: float = 5.0,
) -> list[QuarterHourObservation]:
    """Legacy parsed-event replay; use ``replay_recorded_frames`` for canonical output."""
    ordered = sorted(
        (event for event in events if _event_time(event) is not None or event.get("type") == "heartbeat"),
        key=lambda event: _event_time(event) or datetime.max.replace(tzinfo=timezone.utc),
    )
    book = Level2OrderBook(product_id=product_id)
    processor = BoundaryEventProcessor(product_id=product_id, heartbeat_timeout_seconds=heartbeat_timeout_seconds)
    observations: list[QuarterHourObservation] = []
    for event in ordered:
        observations.extend(process_parsed_event(event=event, book=book, processor=processor))
    return observations


__all__ = [
    "BoundaryEventProcessor",
    "floor_to_quarter_hour",
    "process_parsed_event",
    "replay_recorded_frames",
    "replay_recorded_frames_bounded",
    "CanonicalReplayAccumulator",
    "replay_events",
]
