from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Any

from .boundary_observations import QuarterHourObservation, derive_quarter_hour_observation, require_utc
from .order_book import Level2OrderBook


def floor_to_quarter_hour(timestamp: datetime) -> datetime:
    """Return the exact quarter-hour boundary at or before ``timestamp`` (UTC)."""
    utc = require_utc(timestamp)
    minute = (utc.minute // 15) * 15
    return utc.replace(minute=minute, second=0, microsecond=0)


def _event_time(event: Mapping[str, Any]) -> datetime | None:
    return event.get("event_time_utc") or event.get("time_utc") or event.get("envelope_time_utc")


@dataclass(slots=True)
class BoundaryEventProcessor:
    """Operational, provisional boundary processor for parsed events.

    An observation is derived for every exact quarter-hour boundary crossed
    in this stream. The final canonical ledger must instead be generated by
    :func:`replay_recorded_frames` over sealed source frames.
    """

    product_id: str
    heartbeat_timeout_seconds: float = 5.0
    last_heartbeat_at: datetime | None = None
    gap_since_sync: bool = True
    _last_boundary_checked: datetime | None = field(default=None, repr=False)

    def observe_heartbeat(self, *, time_utc: datetime) -> None:
        self.last_heartbeat_at = require_utc(time_utc)

    def note_gap(self) -> None:
        self.gap_since_sync = True

    def note_synced(self) -> None:
        self.gap_since_sync = False

    def observe(self, *, book: Level2OrderBook, event_time_utc: datetime | None) -> list[QuarterHourObservation]:
        """Emit observations for every quarter-hour boundary newly crossed as of ``event_time_utc``."""
        if event_time_utc is None:
            return []
        event_time_utc = require_utc(event_time_utc)
        floor = floor_to_quarter_hour(event_time_utc)
        if self._last_boundary_checked is None:
            # Bootstrap: allow the very first quarter-hour containing this event to be
            # eligible for emission without walking arbitrarily far into the past.
            self._last_boundary_checked = floor - timedelta(minutes=15)
        boundaries: list[datetime] = []
        cursor = self._last_boundary_checked + timedelta(minutes=15)
        while cursor <= floor:
            boundaries.append(cursor)
            cursor += timedelta(minutes=15)
        observations: list[QuarterHourObservation] = []
        for boundary in boundaries:
            if book.is_synced():
                observations.append(
                    derive_quarter_hour_observation(
                        book=book, timestamp_utc=boundary, product_id=self.product_id,
                        last_heartbeat_at=self.last_heartbeat_at,
                        heartbeat_timeout_seconds=self.heartbeat_timeout_seconds,
                        integrity_reason="sequence_gap" if self.gap_since_sync else None,
                    )
                )
            self._last_boundary_checked = boundary
        return observations


def process_parsed_event(
    *,
    event: Mapping[str, Any],
    book: Level2OrderBook,
    processor: BoundaryEventProcessor,
) -> list[QuarterHourObservation]:
    """Apply a parsed event for provisional live processing or legacy replay."""
    event_type = event.get("type")
    observations = processor.observe(book=book, event_time_utc=_event_time(event))
    if event_type == "heartbeat":
        time_utc = event.get("time_utc")
        processor.observe_heartbeat(time_utc=time_utc or datetime.now(timezone.utc))
        return observations
    if event_type not in {"snapshot", "l2_data"}:
        return observations
    sequence_num = event.get("sequence_num")
    if sequence_num is not None and book.last_sequence_num is not None and sequence_num <= book.last_sequence_num:
        # A redelivered/duplicate message for this connection epoch: its
        # effect is already reflected in the book, so it is safely dropped
        # without invalidating the book or marking a gap.
        return observations
    try:
        if event_type == "snapshot":
            book.reset()
            updates = event.get("updates", [])
            book.apply_snapshot(
                product_id=book.product_id,
                levels={
                    "bid": [u for u in updates if u["side"] == "bid"],
                    "ask": [u for u in updates if u["side"] == "ask"],
                },
            )
        else:
            for change in event.get("updates", []):
                book.apply_update(side=change["side"], price=change["price"], quantity=change["quantity"])
    except ValueError:
        processor.note_gap()
        return observations
    if sequence_num is not None:
        book.last_sequence_num = sequence_num
    processor.note_synced()
    return observations


def _connection_field(connection: Any, name: str) -> Any:
    return connection.get(name) if isinstance(connection, Mapping) else getattr(connection, name, None)


def replay_recorded_frames(
    frames: Iterable[tuple[bytes, str, int]],
    *,
    product_id: str,
    session_id: str,
    heartbeat_timeout_seconds: float,
    connections: Iterable[Any] | None = None,
    session_started_at_utc: datetime | None = None,
    session_completed_at_utc: datetime | None = None,
    derived_at_utc: datetime | None = None,
) -> list[QuarterHourObservation]:
    """Finalize raw frames: validate envelope sequences in delivery order, then replay source-time mutations.

    Connection diagnostics may be mappings or objects with ``connection_id``,
    ``connected_at_utc`` and ``disconnected_at_utc`` attributes. A missing
    disconnect is bounded by the next connection's start when known.
    """
    from btc_quarter_hour_engine.acquisition.coinbase_websocket import parse_coinbase_ws_message

    if heartbeat_timeout_seconds < 0:
        raise ValueError("Heartbeat timeout must be nonnegative")
    start = require_utc(session_started_at_utc) if session_started_at_utc is not None else None
    end = require_utc(session_completed_at_utc) if session_completed_at_utc is not None else None
    if start is not None and end is not None and end < start:
        raise ValueError("Session completion precedes session start")

    # Validate envelopes in recorded delivery order before sorting their
    # mutations by source time for boundary reconstruction.
    deliveries: dict[str, list[tuple[int, int, bytes]]] = {}
    for arrival, (raw, connection_id, frame_index) in enumerate(frames):
        if not isinstance(raw, bytes):
            raise TypeError("Recorded frames must retain their original bytes")
        deliveries.setdefault(connection_id, []).append((frame_index, arrival, raw))

    metadata = {
        _connection_field(c, "connection_id"): c for c in (connections or ())
    }
    ids = list(dict.fromkeys([*metadata, *deliveries]))
    timeline: dict[str, list[tuple[datetime, int, int, str, Any, int | None]]] = {}
    bounds: dict[str, tuple[datetime | None, datetime | None]] = {}
    observed_times: list[datetime] = []
    for connection_id in ids:
        sequence: int | None = None
        invalid = False
        actions: list[tuple[datetime, int, int, str, Any, int | None]] = []
        first_time: datetime | None = None
        last_time: datetime | None = None
        for _frame_index, arrival, raw in deliveries.get(connection_id, []):
            try:
                event = parse_coinbase_ws_message(raw)
            except (ValueError, UnicodeError):
                invalid = True
                if last_time is not None:
                    actions.append((last_time, arrival, 0, "malformed", None, sequence))
                continue
            kind = event.get("type")
            envelope = event["envelope"]
            envelope_time = event.get("envelope_time_utc") or event.get("time_utc") or envelope.timestamp_utc
            if envelope_time is not None:
                envelope_time = require_utc(envelope_time)
            current = envelope.sequence_num
            if sequence is not None and current <= sequence:
                continue
            if sequence is not None and current > sequence + 1:
                gap_time = envelope_time
                if kind == "snapshot":
                    gap_time = envelope_time or require_utc(event["event_time_utc"])
                elif kind == "heartbeat":
                    gap_time = require_utc(event["time_utc"])
                elif kind == "l2_data":
                    times = [require_utc(u.get("event_time_utc") or envelope_time) for u in event["updates"]]
                    if times:
                        gap_time = min(times)
                invalid = True
                actions.append((gap_time, arrival, 0, "gap", None, current))
                observed_times.append(gap_time)
                first_time = min(first_time, gap_time) if first_time else gap_time
                last_time = max(last_time, gap_time) if last_time else gap_time
                sequence = current
                continue
            sequence = current
            if kind not in {"snapshot", "l2_data", "heartbeat"}:
                continue
            if kind == "snapshot":
                event_time = envelope_time or require_utc(event["event_time_utc"])
            elif kind == "heartbeat":
                event_time = require_utc(event["time_utc"])
            else:
                times = [require_utc(u.get("event_time_utc") or envelope_time) for u in event["updates"]]
                event_time = min(times) if times else envelope_time
                observed_times.extend(times)
                if times:
                    last_time = max(last_time, *times) if last_time is not None else max(times)
            if event_time is None:
                continue
            observed_times.append(event_time)
            first_time = min(first_time, event_time) if first_time else event_time
            last_time = max(last_time, event_time) if last_time else event_time
            if kind == "heartbeat":
                if not invalid:
                    actions.append((event_time, arrival, 0, "heartbeat", None, None))
                continue
            if event["product_id"] != product_id:
                continue
            if invalid:
                continue
            if kind == "snapshot":
                actions.append((event_time, arrival, 0, "snapshot", event["updates"], current))
            else:
                for offset, update in enumerate(event["updates"]):
                    when = require_utc(update.get("event_time_utc") or envelope_time)
                    actions.append((when, arrival, offset, "update", update, current))
        meta = metadata.get(connection_id)
        # Connection diagnostics are wall-clock ingest times, not Coinbase
        # source times. Comparing them to event-time boundaries mixes clocks.
        disconnected = _connection_field(meta, "source_disconnected_at_utc")
        disconnected = require_utc(disconnected) if disconnected is not None else None
        bounds[connection_id] = (first_time, disconnected)
        timeline[connection_id] = sorted(actions, key=lambda a: (a[0], a[1], a[2]))

    if not observed_times and (start is None or end is None):
        return []
    start = min(start, *observed_times) if start is not None and observed_times else (
        start if start is not None else min(observed_times)
    )
    end = max(end, *observed_times) if end is not None and observed_times else (
        end if end is not None else max(observed_times)
    )
    if end < start:
        return []
    derived_at = require_utc(derived_at_utc) if derived_at_utc is not None else end
    boundary = floor_to_quarter_hour(start)
    if boundary < start:
        boundary += timedelta(minutes=15)
    # The connection epoch active at a boundary is the last one started by
    # that instant. A disconnected interval cannot inherit its old book.
    ordered_ids = sorted(ids, key=lambda cid: (bounds[cid][0] or datetime.max.replace(tzinfo=timezone.utc), ids.index(cid)))
    for cid in ordered_ids[:-1]:
        bounds[cid] = (bounds[cid][0], max(
            (action[0] for action in timeline[cid]), default=bounds[cid][0],
        ))
    books = {cid: Level2OrderBook(product_id=product_id) for cid in ids}
    cursors = {cid: 0 for cid in ids}
    heartbeats: dict[str, datetime | None] = {cid: None for cid in ids}
    state_times: dict[str, datetime | None] = {cid: None for cid in ids}
    state_sequences: dict[str, int | None] = {cid: None for cid in ids}
    reasons: dict[str, str | None] = {cid: None for cid in ids}
    result: list[QuarterHourObservation] = []
    while boundary <= end:
        active: str | None = None
        for cid in ordered_ids:
            connected, disconnected = bounds[cid]
            if connected is not None and connected <= boundary:
                active = cid
        if active is not None:
            connected, disconnected = bounds[active]
            if disconnected is not None and disconnected < boundary:
                active = None
        if active is None:
            result.append(
                derive_quarter_hour_observation(
                    book=Level2OrderBook(product_id=product_id), timestamp_utc=boundary,
                    product_id=product_id, session_id=session_id, derived_at_utc=derived_at,
                    heartbeat_timeout_seconds=heartbeat_timeout_seconds,
                    integrity_reason="connection_unhealthy" if deliveries else "no_synced_snapshot",
                )
            )
        else:
            actions = timeline[active]
            book = books[active]
            while cursors[active] < len(actions) and actions[cursors[active]][0] <= boundary:
                when, _, _, kind, payload, sequence = actions[cursors[active]]
                cursors[active] += 1
                if kind == "heartbeat":
                    heartbeats[active] = when
                    continue
                if kind == "gap":
                    book.invalidate("sequence gap")
                    reasons[active] = "sequence_gap"
                    state_times[active], state_sequences[active] = when, sequence
                    continue
                if kind == "malformed":
                    book.invalidate("malformed_source_state")
                    reasons[active] = "malformed_source_state"
                    state_times[active], state_sequences[active] = when, sequence
                    continue
                if reasons[active] == "sequence_gap":
                    continue
                try:
                    if kind == "snapshot":
                        book.apply_snapshot(
                            product_id=product_id,
                            levels={"bid": [u for u in payload if u["side"] == "bid"],
                                    "ask": [u for u in payload if u["side"] == "ask"]},
                        )
                        reasons[active] = None
                    elif book.is_synced():
                        book.apply_update(side=payload["side"], price=payload["price"], quantity=payload["quantity"])
                except (ValueError, KeyError, TypeError) as exc:
                    book.invalidate(str(exc))
                    if "crossed" in str(exc).lower():
                        reasons[active] = "crossed_book"
                    elif not book.bids and book.asks:
                        reasons[active] = "missing_bid"
                    elif book.bids and not book.asks:
                        reasons[active] = "missing_ask"
                    else:
                        reasons[active] = "malformed_source_state"
                state_times[active], state_sequences[active] = when, sequence
            result.append(
                derive_quarter_hour_observation(
                    book=book, timestamp_utc=boundary, product_id=product_id,
                    session_id=session_id, connection_id=active, source_state_time_utc=state_times[active],
                    source_sequence_num=state_sequences[active], derived_at_utc=derived_at,
                    last_heartbeat_at=heartbeats[active], heartbeat_timeout_seconds=heartbeat_timeout_seconds,
                    integrity_reason=reasons[active],
                )
            )
        boundary += timedelta(minutes=15)
    return result


def replay_events(
    events: Iterable[Mapping[str, Any]],
    *,
    product_id: str,
    heartbeat_timeout_seconds: float = 5.0,
) -> list[QuarterHourObservation]:
    """Legacy parsed-event replay; use ``replay_recorded_frames`` for canonical output."""
    ordered = sorted(
        (event for event in events if _event_time(event) is not None or event.get("type") == "heartbeat"),
        key=lambda event: _event_time(event) or datetime.max.replace(tzinfo=timezone.utc),
    )
    book = Level2OrderBook(product_id=product_id)
    processor = BoundaryEventProcessor(product_id=product_id, heartbeat_timeout_seconds=heartbeat_timeout_seconds)
    observations: list[QuarterHourObservation] = []
    for event in ordered:
        observations.extend(process_parsed_event(event=event, book=book, processor=processor))
    return observations


__all__ = [
    "BoundaryEventProcessor",
    "floor_to_quarter_hour",
    "process_parsed_event",
    "replay_recorded_frames",
    "replay_events",
]
