from __future__ import annotations

from btc_quarter_hour_engine.storage.forward_schema import (
    COINBASE_WS_RAW_SEGMENT_SCHEMA_VERSION,
    FORWARD_SOURCE,
)

RESEARCH_DATASET_SCHEMA_VERSION = "1"
RESEARCH_MANIFEST_SCHEMA_VERSION = "1"
RESEARCH_BOUNDARY_SCHEMA_VERSION = "1"
RESEARCH_TARGET_SCHEMA_VERSION = "1"

DATA_KIND_RESEARCH_BOUNDARIES = "canonical_boundaries"
DATA_KIND_RESEARCH_TARGETS = "direction_targets"
RESEARCH_INPUT_MODE = "sealed_prefix_snapshot"

__all__ = [
    "COINBASE_WS_RAW_SEGMENT_SCHEMA_VERSION",
    "DATA_KIND_RESEARCH_BOUNDARIES",
    "DATA_KIND_RESEARCH_TARGETS",
    "FORWARD_SOURCE",
    "RESEARCH_BOUNDARY_SCHEMA_VERSION",
    "RESEARCH_DATASET_SCHEMA_VERSION",
    "RESEARCH_INPUT_MODE",
    "RESEARCH_MANIFEST_SCHEMA_VERSION",
    "RESEARCH_TARGET_SCHEMA_VERSION",
]
